### ISSUE TITLE
missing path in train_assist_path and anchor_path in args.py

### ISSUE THREAD

**Issue by neilwen987** [wangyucheng1234/BerVAE#1]
<img width="520" alt="image" src="https://github.com/wangyucheng1234/BerVAE/assets/56498265/32bb0dbd-8253-4e69-87fc-9fcc83161d2b">
i didn't find train_assist_path and anchor_path in args.py, can you show me how to set those path?

**Comment by wangyucheng1234** [comment]
I implement the model based on [BTH](https://github.com/Lily1994/BTH/tree/main). You can either comment out all the code lines related to train_assist_path and anchor_path, or download the data from [BTH/BTH/data](https://github.com/Lily1994/BTH/tree/main/BTH/data) and set the path in utils.args correspondingly. 

Let me know if you have any other questions.
